server:
  port: ${PORT:8080}
spring:
  application:
    name: "ch_ms_products"
  devtools:
    add-properties: false
  profiles:
    include: ${SPRING_PROFILE_INCLUDE:local}
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: ${ALLOWED_ORIGINS:"http://localhost:4200,http://localhost:8081"}
